### ISSUE TITLE
Programación (Revisión 2 y Documentación)

### ISSUE THREAD

**Issue by HebePereyra** [ISPC-PROYECTOS/ARG-broker#10]
Realizar correcciones de revisión 1 y proceder a :
Documentar el diseño especificando: 
Un título significativo. Debe reflejar el propósito del sistema. 
Una breve descripción que explique el contexto, objetivo y alcance del diagrama. 
Nomenclatura elegida para nombres de clases, atributos y métodos.
Comentarios y/o notas que se considere necesario para proporcionar información adicional o explicar decisiones de diseño.

**Comment by ConsueloViramont** [comment]
Documentacion corregida.

**Comment by MarielarosaSZ** [comment]
Se realizaron correcciones para mejorar  el Diagrama de clases
