### ISSUE TITLE
Base de Datos (Documentación)

### ISSUE THREAD

**Issue by HebePereyra** [ISPC-PROYECTOS/ARG-broker#7]
Documentar el diseño de la base de datos, incluyendo una pequeña descripción de cada tabla. Y las aclaraciones que creas necesarias en cada una de ellas. Por ejemplo si se realizó una suposición de algo que no estaba en el enunciado y eso determinó que una relación es uno a muchos, cuando se podría haber interpretado por una ambigüedad que podía ser muchos a muchos, dejar asentada tal suposición.

**Comment by ConsueloViramont** [comment]
Revisado. Con comentarios que fueron discutidos.

**Comment by dataulix** [comment]
Se analizó y se decidió el diseño.
